### PR TITLE
Upload command

### PR DESCRIPTION
**Pull request by nstudach**
Added command upload, uploading data to the PTO
Added argparse options to command measure.
Added more functionality to command metadata

### CODE REVIEW

**Comment by nstudach** [comment]
I did find a bug with argparser argument wrongly named

**Comment by irl** [comment]
Wow! So GitHub will allow me to delete commits from @nstudach's master branch and then because there's no differences close the PR which then prevents me from pushing the rebased commits. Did not expect that...

**Comment by nstudach** [comment]
¯\_(ツ)_/¯
Is it gone? 
Luckily I do have it still in another branch.

**Comment by irl** [comment]
I have rebased the branch so that it only shows changes since the latest master. You can see the review in #251. You might want to clone my branch there to work on it.

**Pull request closed without merging**
