### PR TITLE
Adds a combiner for the DSCP plugin (Closes: #121)

### PR DESCRIPTION
**Pull request by irl**
Need review on the conditions probably more than a review of the code.

### CODE REVIEW

**Comment by irl** [comment]
@britram How did conditions with values work? Perhaps for the seen markings on packets in the reverse direction should be values, not boolean conditions if the PTO can support this.

**Comment by britram** [comment]
@irl PTO can support this: values are (presently) integers, as can codepoints be. So the condition for something could be something like `dscp_<codepoint>_reply: <reverse_codepoint>`...

(Do you want to make this change and I'll review that?)

**Comment by irl** [comment]
@britram How's this?

```
"conditions": ["dscp.48.connectivity.works", "dscp.48.replymark:0", "dscp.0.replymark:0"]
```

**Comment by britram** [comment]
LGTM. do it, ping me when the PR is ready again.

thanks, cheers,

Brian

**Comment by irl** [comment]
It already was. I rebased.

**Comment by irl** [comment]
@britram ^

**Pull request merged**
